### ISSUE TITLE
daedalus server crash while exploring

### ISSUE THREAD

**Issue by Saereth** [breakinblocks/nutsandbolts#127]
// Why did you do that?

Time: 9/13/16 8:26 AM
Description: Exception ticking world

java.lang.UnsupportedOperationException
        at java.util.Collections$UnmodifiableList.remove(Collections.java:1317)
        at com.abecderic.labyrinth.worldgen.room.RoomGenerator.getBlockState(RoomGenerator.java:142)
        at com.abecderic.labyrinth.worldgen.room.RoomGenerator.getBlockState(RoomGenerator.java:170)
        at com.abecderic.labyrinth.worldgen.room.RoomGenerator.applyReplacement(RoomGenerator.java:108)
        at com.abecderic.labyrinth.worldgen.room.RoomGenerator.generateRoomAt(RoomGenerator.java:91)
        at com.abecderic.labyrinth.worldgen.LabyrinthChunkGenerator.func_185931_b(LabyrinthChunkGenerator.java:124)
        at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1000)
        at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:974)
        at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
        at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
        at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
        at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

**Comment by Saereth** [comment]
fixed in update
