### ISSUE TITLE
client crash when viewing ItemGolemPlacer in NEI

### ISSUE THREAD

**Issue by keturn** [breakinblocks/nutsandbolts#138]
```
-- Head --
Stacktrace:
	at com.kentington.thaumichorizons.common.items.ItemGolemPlacer.func_82790_a(ItemGolemPlacer.java:52)
	at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:485)
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:565)

-- Item being rendered --
Details:
	Item Type: com.kentington.thaumichorizons.common.items.ItemGolemPlacer@4709bc03
	Item Aux: 4
	Item NBT: null
	Item Foil: false
Stacktrace:
	at codechicken.nei.guihook.GuiContainerManager.drawSlotItem(GuiContainerManager.java:489)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:270)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)

-- Screen render details --
Details:
	Screen name: codechicken.nei.recipe.GuiUsageRecipe

```

full crash report at https://gist.github.com/keturn/1d9fcb1c65efa02f948dc15b8115e8df

my crash looks to be equivalent to https://openeye.openmods.info/crashes/20d1fd0650c2fa44936c9c369242c7d5

Seems like Thaumic Horizons hasn't been updated in quite a while, but perhaps there's a new maintainer recently? https://github.com/Hoborific/ThaumicHorizons [forum post](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2361575-thaumic-horizons-v1-1-9-thaumcraft-4-addon?page=104#c2096)

**Comment by Saereth** [comment]
I tried contacting him to see if he was maintaining/bug fixing, no luck, may have to just disable that item for now.
