### ISSUE TITLE
client crash when viewing diamond in Minechem

### ISSUE THREAD

**Issue by keturn** [breakinblocks/nutsandbolts#139]
Client crashes when inserting a diamond into a minechem microscope, or attempting to view the diamond page in the chemist's journal.

```
-- Head --
Stacktrace:
        at minechem.item.chemistjournal.ChemistJournalItem.setActiveStack(ChemistJournalItem.java:94)
        at minechem.item.chemistjournal.ChemistJournalGui.showRecipesForStack(ChemistJournalGui.java:149)
        at minechem.item.chemistjournal.ChemistJournalGui.onSlotClick(ChemistJournalGui.java:143)
        at minechem.item.chemistjournal.ChemistJournalGui.func_73864_a(ChemistJournalGui.java:124)
        at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
        at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
        at minechem.gui.GuiContainerTabbed.func_146274_d(GuiContainerTabbed.java:334)
        at minechem.item.chemistjournal.ChemistJournalGui.func_146274_d(ChemistJournalGui.java:419)
        at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
        at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)

-- Affected screen --
Details:
        Screen name: minechem.item.chemistjournal.ChemistJournalGui
```

full crash report at https://gist.github.com/keturn/e08f63bd9e463f5fa12694458b34e119

**Comment by Saereth** [comment]
odd, I have not been able to reproduce this issue, I see you're using multimc though I may try moving it over there to see, have you added/removed any mods as well?

**Comment by keturn** [comment]
Hmm. I already disabled optifine before making the crash report linked earlier.

Wondered if it was a resource pack thing, so just disabled the resource pack I'm using, still crashed.

And the only other mod in my mods folder that wasn't in the multimc zip you provided is, uh, Better Loading Screen? which sounds unlikely to be interacting here.
