### ISSUE TITLE
Wireless Redstone crashes server on boot

### ISSUE THREAD

**Issue by keturn** [breakinblocks/nutsandbolts#147]
I can work around this by deleting the RedstoneEther directories from the dimension involved, but the problem pops up again a few days later.

No idea why, I doubt we have players active in these dimensions **at all**, let alone using Wireless Redstone there.

```
---- Minecraft Crash Report ----
// You're mean.

Time: 4/14/17 12:03 PM
Description: Exception in server tick loop

java.lang.RuntimeException: java.io.EOFException
	at codechicken.wirelessredstone.core.SaveManager.loadFreqMap(SaveManager.java:446)
	at codechicken.wirelessredstone.core.SaveManager.loadEther(SaveManager.java:567)
	at codechicken.wirelessredstone.core.RedstoneEtherServer.addEther(RedstoneEtherServer.java:54)
	at codechicken.wirelessredstone.core.RedstoneEther.loadServerWorld(RedstoneEther.java:114)
	at codechicken.wirelessredstone.core.WRCoreEventHandler.onWorldLoad(WRCoreEventHandler.java:29)
```

[crash-2017-04-14_12.03.34-server.txt](https://github.com/breakinblocks/nutsandbolts/files/922285/crash-2017-04-14_12.03.34-server.txt)

**Comment by Saereth** [comment]
yeah this has been around for ages and never got resolved im just gonna remove it tbh its not really nescesary as rftools can provide the same functionality
