### ISSUE TITLE
server crash when using hoe with ResourcefulCrops

### ISSUE THREAD

**Issue by keturn** [breakinblocks/nutsandbolts#149]
```
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
        at tehnut.resourceful.crops.util.ChatUtil.sendNoSpamMessages(ChatUtil.java:68)
        at tehnut.resourceful.crops.util.ChatUtil.sendNoSpamClient(ChatUtil.java:174)
        at tehnut.resourceful.crops.util.ChatUtil.sendNoSpamClient(ChatUtil.java:165)
        at tehnut.resourceful.crops.block.BlockRCrop.doReqInfo(BlockRCrop.java:283)
        at tehnut.resourceful.crops.block.BlockRCrop.func_149727_a(BlockRCrop.java:149)
        at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:376)
```

I'd just right-clicked on a witherwheat plant with a hoe (in pursuit of a ResourcefulCrops achievement).

[crash-2017-04-30_05.38.37-server.txt](https://github.com/breakinblocks/nutsandbolts/files/966820/crash-2017-04-30_05.38.37-server.txt)

**Comment by joral** [comment]
re-created and reported to mod author:
https://github.com/TehNut/ResourcefulCrops/issues/49

**Comment by Saereth** [comment]
This is will take a custom build of RC, will fix later
