### ISSUE TITLE
Instant Crash, arcane crafting terminal + floating candles

### ISSUE THREAD

**Issue by DarkLordIce** [breakinblocks/nutsandbolts#39]
Attempted to craft floating candles (using black candle) in the Thaumic Energistics crafting terminal.  Client crashed to desktop as soon as all the ingredients were added.  Since the terminal retains the last  thing crafted if mats remain, it now auto crashes me any time I access the terminal.  Assume it will do the same to others.  Have not tested it in a regular arcane crafting table to determine if the issue lies with the pattern or the terminal.

Crash report stuff:

- Minecraft Crash Report ----
// Don't do that.

Time: 2/1/15 7:44 PM
Description: Rendering item

java.lang.ArrayIndexOutOfBoundsException: 32767
	at thaumcraft.common.blocks.BlockCandle.func_149741_i(BlockCandle.java:62)
	at net.minecraft.client.renderer.RenderBlocks.func_147800_a(RenderBlocks.java:8810)
	at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:446)
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:565)
	at codechicken.nei.guihook.GuiContainerManager.drawSlotItem(GuiContainerManager.java:488)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:270)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
	at thaumicenergistics.gui.abstraction.AbstractGuiWithScrollbar.func_73863_a(AbstractGuiWithScrollbar.java:192)
	at thaumicenergistics.gui.GuiArcaneCraftingTerminal.func_73863_a(GuiArcaneCraftingTerminal.java:737)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1355)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Saereth** [comment]
This is fixed in the new version of thaumic energistics
