### ISSUE TITLE
Malisis Doors forcefields still causing crash

### ISSUE THREAD

**Issue by Saereth** [breakinblocks/nutsandbolts#41]
Client crash on connect with:

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 1/18/15 12:18 AM
Description: Rendering Block Entity

java.lang.NullPointerException: Rendering Block Entity
	at net.malisis.doors.door.tileentity.ForcefieldTileEntity.getOriginMetadata(ForcefieldTileEntity.java:58)
	at net.malisis.doors.door.tileentity.ForcefieldTileEntity.isOpened(ForcefieldTileEntity.java:76)
	at net.malisis.doors.door.renderer.ForcefieldRenderer.render(ForcefieldRenderer.java:87)
	at net.malisis.core.renderer.MalisisRenderer.func_147500_a(MalisisRenderer.java:401)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:483)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.malisis.doors.door.tileentity.ForcefieldTileEntity.getOriginMetadata(ForcefieldTileEntity.java:58)
	at net.malisis.doors.door.tileentity.ForcefieldTileEntity.isOpened(ForcefieldTileEntity.java:76)
	at net.malisis.doors.door.renderer.ForcefieldRenderer.render(ForcefieldRenderer.java:87)
	at net.malisis.core.renderer.MalisisRenderer.func_147500_a(MalisisRenderer.java:401)

-- Block Entity Details --
Details:
	Name: forcefieldTileEntity // net.malisis.doors.door.tileentity.ForcefieldTileEntity
	Block type: ID #2112 (tile.forcefieldDoor // net.malisis.doors.door.block.ForcefieldDoor)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-2052,59,2174), Chunk: (at 12,3,14 in -129,135; contains blocks -2064,0,2160 to -2049,255,2175), Region: (-5,4; contains chunks -160,128 to -129,159, blocks -2560,0,2048 to -2049,255,2559)
	Actual block type: ID #2112 (tile.forcefieldDoor // net.malisis.doors.door.block.ForcefieldDoor)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:483)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224)

**Comment by Saereth** [comment]
This is fixed in the latest version
